### PR TITLE
Adds --locale parameter

### PR DESCRIPTION
**Pull request by BorisNaguet**
This new parameter allow to generate 
```json
"_locale": "en"
```
at the top of the arb file.

This is important to solve issues like:
https://github.com/dart-lang/intl/issues/133

Please note that I chose  `_locale` instead of `@@locale` because the last one currently doesn't work with _generate_from_arb_

### CODE REVIEW

**Comment by alan-knight** [comment]
Which does ARB prefer? Maybe we should fix `@@locale` in generate_from_arb?

**Comment by alan-knight** [comment]
Also, this one doesn't show cla:yes, but your others do. Do you need to do it from a different account?

**Comment by BorisNaguet** [comment]
For CLA, I signed it with my google email account ('lespetitesphotos'), but this is not my Github email (it's set as a backup email which seems to be detected by the bot).
 Apparently the Github account that does the PR doesn't count, it's the email set in the commit that must sign CLA.
 That's why I committed with that 'lespetitesphotos' email.
 So it should work for this PR, like for the other 2

**Comment by BorisNaguet** [comment]
Apparently cla:yes appeared magically after I commented...

I'm really new to the arb format, but fromthe 1st examples, `"@@locale"` seems to be the standard:
https://github.com/googlei18n/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#global-attributes

I proposed #17 to correct the bug. If you integrate it, this PR should be changed to favor this field.

**Pull request closed without merging**
