### PR TITLE
Migration to null safety and Flutter 2.0

### LINKED ISSUE #134: It's incompatible with Flutter 2 released today
The subject says it all.

### PR DESCRIPTION
**Pull request by jaumard**
fix #134

### CODE REVIEW

**Comment by deepak786** [comment]
when this pull request will be merged and released? any plan or idea?

**Comment by jaumard** [comment]
> when this pull request will be merged and released? any plan or idea?

Until it is you can use `intl_generator` it's what it's under this PR basically :)

**Comment by Holofox** [comment]
Getters doesn't work:

```console
Skipping invalid Intl.message invocation
    <Intl.message('Confirm', name: 'confirm', desc: 'confirm')>
    reason: Calls to Intl must be inside a method, field declaration or top level declaration.
    from lib/core/infrastructure/intl/jump_localizations.dart    line: 1477, column: 25
```

```dart
  String get confirm => Intl.message(
        'Confirm',
        name: 'confirm',
        desc: 'confirm',
      );
```

But method work:
```dart
  String confirm() => Intl.message(
        'Confirm',
        name: 'confirm',
        desc: 'confirm',
      );
```

**Comment by waitwalker** [comment]
Approved

**Comment by etiennecadicidean** [comment]
Since it was approved,  when do we expect it to be merged ?

**Comment by edblocker** [comment]
> Since it was approved, when do we expect it to be merged ?

I'm wondering this too

**Comment by enginebai** [comment]
> Since it was approved, when do we expect it to be merged ?

I'm wondering too, waiting for this package migration is such a huge block for the project that is ready to migrate flutter 2. The flutter team promotes 2.x very hard, but the official package migration runs so slow.

**Comment by jaumard** [comment]
Like I said guys you can use `intl_generator ` on pub, it's what is contain in this PR if you don't want to wait.

**Comment by deepak786** [comment]
@jaumard why the `intl_generator` putting the `placeholders_order` key in the .arb files

Screen Shot 2021-10-02 at 12 30 20 AM
.

**Comment by jaumard** [comment]
@deepak786 I added this on my side to be able to use ARB files directly on the fly with `flutter_jimtl` and do OTA updates of ARB. You can ignore that :)

**Comment by deepak786** [comment]
@jaumard is there a way so that this parameter will not be added to the files. Like something can I add to the build command?

**Pull request closed without merging**
