### PR TITLE
Raise analyser dependency to <0.31.3

### PR DESCRIPTION
**Pull request by aam**
This is to fix https://github.com/flutter/flutter/issues/15261

### CODE REVIEW

**Comment by aam** [comment]
@vsmenon can you suggest how to land this while @alan-knight away?

cc @jason-simmons

**Comment by vsmenon** [comment]
@aam do we just need to land or publish as well?

**Comment by aam** [comment]
land and publish, yes. Flutter will then bump it dependency up to the published version.

**Comment by matanlurey** [comment]
This package is internal first AFAIK.

**Comment by aam** [comment]
@matanlurey wrote:
> This package is internal first AFAIK.

What does it mean "internal first"?

**Comment by vsmenon** [comment]
Right!  It's developed in the internal google repository.  This is basically a mirror of that.

**Comment by vsmenon** [comment]
@matanlurey - if we land internally, does this get updated automatically?  If not, what's the step?  (I'm assuming we're using the same process for angular.dart.)

**Comment by matanlurey** [comment]
I'm not sure honestly, perhaps?

**Comment by aam** [comment]
> Right! It's developed in the internal google repository. This is basically a mirror of that.

Oh, got you!

> if we land internally, does this get updated automatically? If not, what's the step?

Looking closer I see that [PR one before last](https://github.com/dart-lang/intl_translation/commit/67413a051b46416e3140ca220a92ba35409f0a8c) was done with https://github.com/google/moe.

**Comment by aam** [comment]
Closing this as I opened https://github.com/dart-lang/intl_translation/pull/24 with moe-created sync of internal repo to github.

**Pull request closed without merging**
