### PR TITLE
Clean up two warnings

### PR DESCRIPTION
**Pull request by bwilkerson**

### CODE REVIEW

**Review by devoncarew — APPROVED** [review]

**Comment by bwilkerson** [comment]
Looks like this might need to be updated from Travis in order to get the build to pass, which is work I'm not familiar with.

**Comment by devoncarew** [comment]
The CI will almost certainly need to be switched from using travis to github actions.

**Comment by bwilkerson** [comment]
Is there a plan for getting the CI converted?

**Comment by devoncarew** [comment]
Not that I'm aware of, but the work is essentially deleting the .travis file and adding a new `.github/workflow/dart.yml`; Michael wrote a medium article about it.

**Comment by bwilkerson** [comment]
@mit-mit Is there someone that can take on the Travis work?

**Comment by mit-mit** [comment]
It looks like @athomas already did it, but [the PR](https://github.com/dart-lang/intl_translation/pull/132/files) never landed. Alex, recall why?

**Comment by athomas** [comment]
@mit-mit It's an a package with an internal source of truth. So the maintainer needs to import the PR to g3 and on the next export it will be closed.

**Pull request closed without merging**
