### PR TITLE
Adding lints from effective_dart to ignored

### PR DESCRIPTION
**Pull request by jpc-ae**
Added public_member_api_docs, avoid_catches_without_on_clauses & type_annotate_public_apis as appropriate to list of ignored lints as are both part of effective_dart and throw annoying messages.

### CODE REVIEW

**Comment by marcelgarus** [comment]
Would it also be possible to ignore the `non_constant_identifier_names` lint?
We use underscores in keys to denote hierarchies, for example `app_emptyState_retry` and as a result, we get hundreds of linter warnings. (would close #90)

**Comment by jpc-ae** [comment]
> Would it also be possible to ignore the `non_constant_identifier_names` lint?
> We use underscores in keys to denote hierarchies, for example `app_emptyState_retry` and as a result, we get hundreds of linter warnings. (would close #90)

Honestly, that seems like an edge case that, unless you have a lot of duplicate string names, could better be handled with nested classes (though it's admittedly more verbose) as below (tested working):

Inside localizations class...
```dart
  _AppStrings get app => _AppStrings(locale) ;
```

Inside the localizations library dart file:
```dart
class _AppStrings {
  _AppStrings(this.locale);

  final String locale;

  _EmptyStateStrings get emptyState => _EmptyStateStrings(locale) ;
  }
}

class _EmptyStateStrings {
  _EmptyStateStrings(this.locale);

  final String locale;

  String get retry {
    return Intl.message(
      'Retry',
      name: 'retry',
      desc: 'Try something again.',
      locale: locale,
    );
  }
}
```

Would that work for you? If you prefer keeping your naming style, perhaps consider loading a json file into a mapped field and calling the text by key in your app. If you really want app_emptyState_retry added to the ignores, I think a main dart developer would need to look over this comment and weigh in.

**Comment by marcelgarus** [comment]
Loading a JSON file dynamically into the app just to support certain names feels a little work-around-y to me. More importantly, it doesn't integrate well into our workflow: We're using `.arb` files for the localization of the app and [Localizely](https://localizely.com/)'s [ VSCode plugin](https://github.com/localizely/flutter-intl-vscode/issues) for turning these into <kbd>intl_translation</kbd> code. Under the hood, the plugin uses [<kbd>intl_utils</kbd>](https://pub.dev/packages/intl_utils), which doesn't support dots in names (yet). Because it's not hosted on GitHub (yet?), I already mailed the maintainer, @aleksakrstic, who had a convincing argument for the other side: Autocomplete works better with underscores – you don't need to know the type hierarchy in advance to find a particular string. Also, it wouldn't hurt to keep the option of using underscores open, so I'd argue for disabling the lint.
That being said, if you need this to get merged quickly, it wouldn't hurt to open another PR for this and move the discussion over there. What do you think?

**Comment by jpc-ae** [comment]
That is a convincing argument, I don't mind adding it to the pull request, though judging by how quiet this project is I'm not holding my breath for it to get merged any time soon.

Currently I'm just manually editing (with backup of course) my local project's intl_translation-0.17.9 > generate_localized.dart file to ignore the lints when I run it. Not sure if that would help your team in the short term as well.

**Comment by marcelgarus** [comment]
Great, thank you 👍
In the short term, we'll just depend on your fork of the repo. But it would be nice to have a more permanent solution, so I'm crossing my fingers for this to get merged.

**Comment by TheManuz** [comment]
I propose to use:

`// ignore_for_file: type=lint`

[Related thread](https://github.com/dart-lang/sdk/issues/46957#issuecomment-992068403)

This will make the generated file future-proof and let the users add their own lint rules without receiving lint warnings from generated file.

**Comment by mosuem** [comment]
Closing, as we are ignoring all lints now.

**Pull request closed without merging**
